### ISSUE TITLE
SAMD51J symbol not in kicad-libs repository?

### ISSUE THREAD

**Issue by adamwolf** [chickadee-tech/pyoven#1]
I tried to take a look today, and when I downloaded kicad-libs, I only see one component, SAMD21J.  I didn't see any other branches.

Is there somewhere else I can find that symbol?

Thanks!

**Comment by tannewt** [comment]
Check again. I hadn't pushed my latest changes to it. Why are you interested in it? There are a couple fixes to the design I haven't done and pushed yet.

**Comment by adamwolf** [comment]
Just curious about the schematic, that's all.  Collecting some examples of
SAMD51 stuff.

**Comment by tannewt** [comment]
Cool cool. The current schematic has 3v3 on vddcore which is wrong. Once I cut that trace it worked just fine.

I saw you do the Mac packaging for Kicad. I really appreciate it! I'm a huge fan of Kicad.

**Comment by adamwolf** [comment]
Thanks!
